-- Create Schema
CREATE SCHEMA IF NOT EXISTS "home budget application"

-- Creating custom types

CREATE TYPE "home budget application".user_role_in_group AS
enum ( 'admin', 'guest' )

CREATE TYPE "home budget application".transaction_type AS
enum ( 'deposit', 'withdraw' )

-- Creating tables

-- Categories
CREATE  TABLE "home budget application".categories ( 
	category_id          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	category_name        varchar(100)  NOT NULL  ,
	category_description varchar(1000)    ,
	CONSTRAINT pk_categories PRIMARY KEY ( category_id )
 ) 

-- Currency
CREATE  TABLE "home budget application".currency ( 
	currency_id          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	currency_name        varchar(100)    ,
	currency_short       char(3)  NOT NULL  ,
	dollar_rate          numeric(100,4)  NOT NULL  ,
	CONSTRAINT pk_currency PRIMARY KEY ( currency_id )
 )

-- Sessions
CREATE  TABLE "home budget application".sessions ( 
	session_id           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	creation_time        timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	expiration_time      timestamp DEFAULT CURRENT_TIMESTAMP + INTERVAL '86400 seconds' NOT NULL  ,
	hash                 text DEFAULT md5(random()::text || clock_timestamp()::text) NOT NULL  ,
	CONSTRAINT pk_sessions PRIMARY KEY ( session_id )
 )

-- Subcategories
CREATE  TABLE "home budget application".subcategories ( 
	subcategory_id       integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	subcategory_name     varchar(100)  NOT NULL  ,
	subcategory_description varchar(1000)    ,
	category_id          integer  NOT NULL  ,
	CONSTRAINT pk_subcategories PRIMARY KEY ( subcategory_id ),
	CONSTRAINT unq_subcategories_category_id UNIQUE ( category_id ) 
 ) 

 -- Transactions
 CREATE  TABLE "home budget application".transactions ( 
	transaction_id       integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	transaction_time     timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	"value"              numeric(10,2)    ,
	transaction_type     "home budget application".transaction_type  NOT NULL  ,
	currency_id          integer  NOT NULL  ,
	category_id          integer  NOT NULL  ,
	subcategory_id       integer    ,
	CONSTRAINT pk_transactions PRIMARY KEY ( transaction_id ),
	CONSTRAINT unq_transactions_currency_id UNIQUE ( currency_id ) 
 ) 

 -- Wallets
 CREATE  TABLE "home budget application".wallets ( 
	wallet_id            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	currency_id          integer  NOT NULL  ,
	bilance              money DEFAULT 0 NOT NULL  ,
	wallet_name          varchar(100)  NOT NULL  ,
	creation_time        timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	CONSTRAINT pk_wallets PRIMARY KEY ( wallet_id )
 ) 

 --Countries
 CREATE  TABLE "home budget application".countries ( 
	country_id           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	country_name         varchar(200)  NOT NULL  ,
	country_code         char(5)    ,
	currency_id          integer  NOT NULL  ,
	CONSTRAINT pk_countries PRIMARY KEY ( country_id )
 ) 

 -- Users
 CREATE  TABLE "home budget application".users ( 
	user_id              integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	name                 varchar(100)  NOT NULL  ,
	surname              varchar(100)    ,
	nick_name            varchar(100)  NOT NULL  ,
	creation_time        timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	update_time          timestamp    ,
	email                varchar(100)  NOT NULL  ,
	phone_number         varchar(15)    ,
	user_password        varchar(100)  NOT NULL  ,
	salt                 varchar(100)  NOT NULL  ,
	country_id           integer  NOT NULL  ,
	CONSTRAINT pk_users PRIMARY KEY ( user_id )
 ) 

CREATE UNIQUE INDEX unq_users_nick_name ON "home budget application".users ( nick_name ) 

-- Users_sessions
CREATE  TABLE "home budget application".users_sessions ( 
	session_id           integer  NOT NULL  ,
	user_id              integer  NOT NULL  ,
	CONSTRAINT unq_users_sessions_session_id UNIQUE ( session_id ) 
 ) 

 -- Users_wallets
 CREATE  TABLE "home budget application".users_wallets ( 
	wallet_id            integer  NOT NULL  ,
	user_id              integer  NOT NULL  ,
	CONSTRAINT unq_users_walets_wallet_id UNIQUE ( wallet_id ) 
 ) 

 -- Groups
CREATE  TABLE "home budget application".groups ( 
	group_id             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY   ,
	group_name           varchar(100) DEFAULT 'New Group' NOT NULL  ,
	group_description    varchar(1000)    ,
	group_photo          varchar(1000)    ,
	creation_time        timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	update_time          timestamp    ,
	owner_id             integer    ,
	CONSTRAINT pk_groups PRIMARY KEY ( group_id )
 ) 

 -- Users groups
 CREATE  TABLE "home budget application".users_groups ( 
	user_role            "home budget application".user_role_in_group  NOT NULL DEFAULT 'guest'  ,
	join_time            timestamp DEFAULT CURRENT_TIMESTAMP   ,
	group_id             integer    ,
	user_id              integer    ,
	CONSTRAINT unq_users_groups_user_id UNIQUE ( user_id ) 
 ) 

 -- Users groups transactions
 CREATE  TABLE "home budget application".users_groups_transactions ( 
	transaction_time     timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
	user_id              integer  NOT NULL  ,
	group_id             integer    ,
	transaction_id       integer  NOT NULL  ,
	wallet_id            integer  NOT NULL  ,
	CONSTRAINT unq_users_groups_transactions_user_id UNIQUE ( user_id ) ,
	CONSTRAINT unq_users_groups_transactions_group_id UNIQUE ( group_id ) ,
	CONSTRAINT unq_users_groups_transactions_transaction_id UNIQUE ( transaction_id ) 
 ) 

 ALTER TABLE "home budget application".countries
    ADD CONSTRAINT fk_countries_currency
    FOREIGN KEY ( currency_id )
    REFERENCES "home budget application".currency( currency_id )
    ON UPDATE CASCADE 

ALTER TABLE "home budget application".groups
    ADD CONSTRAINT fk_groups_users
    FOREIGN KEY ( owner_id )
    REFERENCES "home budget application".users( user_id ) 

ALTER TABLE "home budget application".subcategories
    ADD CONSTRAINT fk_subcategories_categories
    FOREIGN KEY ( category_id )
    REFERENCES "home budget application".categories( category_id ) 

ALTER TABLE "home budget application".transactions
    ADD CONSTRAINT fk_transactions_currency
    FOREIGN KEY ( currency_id )
    REFERENCES "home budget application".currency( currency_id )

ALTER TABLE "home budget application".transactions
    ADD CONSTRAINT fk_transactions_subcategories
    FOREIGN KEY ( subcategory_id )
    REFERENCES "home budget application".subcategories( subcategory_id )  

ALTER TABLE "home budget application".transactions
    ADD CONSTRAINT fk_transactions_categories
    FOREIGN KEY ( category_id )
    REFERENCES "home budget application".categories( category_id )

ALTER TABLE "home budget application".users
    ADD CONSTRAINT fk_users_countries
    FOREIGN KEY ( country_id )
    REFERENCES "home budget application".countries( country_id ) 
    ON UPDATE CASCADE

ALTER TABLE "home budget application".users_groups
    ADD CONSTRAINT fk_users_groups_users
    FOREIGN KEY ( group_id )
    REFERENCES "home budget application".groups( group_id )

ALTER TABLE "home budget application".users_groups
    ADD CONSTRAINT fk_users_groups_users_0
    FOREIGN KEY ( user_id )
    REFERENCES "home budget application".users( user_id )

ALTER TABLE "home budget application".users_groups_transactions
    ADD CONSTRAINT fk_users_groups_transactions_transactions
    FOREIGN KEY ( transaction_id )
    REFERENCES "home budget application".transactions( transaction_id )

ALTER TABLE "home budget application".users_groups_transactions
    ADD CONSTRAINT fk_users_groups_transactions_groups
    FOREIGN KEY ( group_id )
    REFERENCES "home budget application".groups( group_id )

ALTER TABLE "home budget application".users_groups_transactions
    ADD CONSTRAINT fk_users_groups_transactions_users
    FOREIGN KEY ( user_id )
    REFERENCES "home budget application".users( user_id )

ALTER TABLE "home budget application".users_groups_transactions
    ADD CONSTRAINT fk_users_groups_transactions_wallets
    FOREIGN KEY ( wallet_id )
    REFERENCES "home budget application".wallets( wallet_id )
    ON DELETE CASCADE
    ON UPDATE CASCADE 

ALTER TABLE "home budget application".users_sessions
    ADD CONSTRAINT fk_users_sessions_users
    FOREIGN KEY ( user_id )
    REFERENCES "home budget application".users( user_id )
    ON DELETE CASCADE
    ON UPDATE CASCADE 

ALTER TABLE "home budget application".users_sessions
    ADD CONSTRAINT fk_users_sessions_sessions
    FOREIGN KEY ( session_id )
    REFERENCES "home budget application".sessions( session_id )
    ON DELETE CASCADE
    ON UPDATE CASCADE

ALTER TABLE "home budget application".users_wallets
    ADD CONSTRAINT fk_users_walets_users
    FOREIGN KEY ( user_id )
    REFERENCES "home budget application".users( user_id )
    ON DELETE CASCADE
    ON UPDATE CASCADE

ALTER TABLE "home budget application".users_wallets
    ADD CONSTRAINT fk_users_wallets_wallets
    FOREIGN KEY ( wallet_id )
    REFERENCES "home budget application".wallets( wallet_id )
    ON DELETE CASCADE
    ON UPDATE CASCADE

ALTER TABLE "home budget application".wallets
    ADD CONSTRAINT fk_wallets_currency
    FOREIGN KEY ( currency_id )
    REFERENCES "home budget application".currency( currency_id )
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
